services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  web:
    build: .
    command: make api-startup
    volumes:
      - .:/services-api
    ports:
      - "3000:3000"
    env_file: .env
    depends_on:
      - db
